### ISSUE TITLE
get_icov for cg_scaled seems to be broken

### ISSUE THREAD

**Issue by msyriac** [AdriJD/optweight#3]
An error like this happens
```
Traceback (most recent call last):
  File "test_opt.py", line 95, in <module>
    out = solvers.cg_pix_filter(alm,theory_cls,b_ell,lmax,
  File "/gpfs/fs1/home/r/rbond/msyriac/repos/optweight/optweight/solvers.py", line 374, in cg_pix_filter
    return cgobj.filter(alm,benchmark=benchmark,
  File "/gpfs/fs1/home/r/rbond/msyriac/repos/optweight/optweight/solvers.py", line 252, in filter
    output['ialm'] = solver.get_icov()
  File "/gpfs/fs1/home/r/rbond/msyriac/repos/optweight/optweight/solvers.py", line 873, in get_icov
    return self.icov_signal(self.get_wiener(self.x.copy()))
TypeError: get_wiener() takes 1 positional argument but 2 were given
```

because get_icov tries to pass an argument to get_wiener here:
https://github.com/AdriJD/optweight/blob/master/optweight/solvers.py#L505

**Comment by AdriJD** [comment]
Thanks! Well spotted. I have pushed a fix.
